language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: qCGh9HkzsNVaBpvPcAWNd9CJMenfzpIYl+bGIvd15RzE3mLk/i6pkFnGAuUD3WV9/n2gOsCrtGrpxcVOPeAr5SOIkoNOIGbOja+VfSPGD524Q3spfVbGqKsE6mIvq1AIe+Xf+79g+cUr/CwKagewBV5ilwrzYYIYkElY8onQ81hjJXzpDOkqsPKRAg57fsfKbZJQcGXPmPAAXbhGuWTvePFIeh/8WN0IJtU/3K4Gp0qzc/l5iz1zTaMdue9KcDhYqPPytCTzgrdlEqZr8Aq/E5/tWhht5ooR7idBTuXQR8cVSBC9udXkgXmny5F2rDhIW0gmiXMr+zjCKKrKQpLpwFX+N1MHnCy03HHaJRiGGdOua/EOHZYJmfpXx9HVwdB4FRRzArfwBVziM9tYWAKUWjSHGhJHV9xZCLM/p+YTckyX9a6lLu2jMPfcxJnykFYz6eV2xvkMw13h+5Km0X0Pb+wRA3PmYC/ZGvIbqzddZ8a0g3yagda0f6IICFEY4r52Pii2yYeS+AM6LfCLhHVor4NfhA1kncrtRvx4vR6j8urC8fvLQ45qcXjIU4AQlSaMGKNok2N8W6KrYhrd0LlONoW4z1frRwlwszXP7itlDFf6HtfzVa5XLGSrT7lpRMn9sviQK7FzCvqhljUop7ipIeSqlP7CyPxa5f3yQa9vVxM=
  app: lit-temple-66051
  on:
    repo: CaseyVandyke/Fit-Track
