language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: sljGkd1N/hrfsfKh8eNC8qUttoiUR3+XpkogGKn98b63PcSLWQNtF71k92jLklGT1qM9c05sXLSNtKLbJfHc+4U2pWpcivnpqL/9O0Cb27qW8Q+QVa0Ktc4oB/dzfYetsa8ZWzztlLq3F9WMfgqeKvubcNCmkDNLdObbMN5hW+fsBdfeKIJC1sg3W1TjwYMa9U5hm/Xsp/GQTq+jIJwSIRrU4P1Tgpx5JWjka3L4l92SS7U5y9rs1HvYN+oM8pArq2HFgB5E0HrRigUBENiN1atLT+BhYf+jqeFhaZqbPu3zxLTVwqE066gXu2sP6/yz4ZUoEVMlg9y73iEAuRUxisdXceAZAyU2cO0LKHyrlWy4jBb3DHTJ9AmVbB1YqfhvMTMY/EXEKGe4lgj+oCg133fxTGtTiYB0b8VS3Yk+m+Csylezk7T4Z3DHVqAKpSP/SalDahPr0zG+Gtk6pmxTzMuJksZa/U7ew1jZhqGvzbY/Qn+m8imY/8wZPfFoxaFXoDLKjhKHRvn7x90TaFxeNOghVWL8kOs+JTYmOcuxRa7XnWa1LvvLQ1fWyAuMYjTe2XA0rdIByEVTV/kC/GTfH5+LdB1x6b1zGd1XmDmBQ1XhUFX5795Fmg+yLREahk95ppPXbp/kLkSuUQc2QezBsNRr1mcxH7662/W6+cTJEF8=
  app: damp-savannah-65805
  on:
    repo: CaseyVandyke/Fit-Track
